/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\2b12NZh0CH30EQ5HjMDwTuDtuK2WIeonJSpJWc77wP1WrXJcX8RZOG.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2b12NZh0CH30EQ5HjMDwTuDtuK2WIeonJSpJWc77wP1WrXJcX8RZOG.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.UnionAvatars_Body.geometry} material={materials.UnionAvatars_Body} skeleton={nodes.UnionAvatars_Body.skeleton} />
      <skinnedMesh geometry={nodes.UnionAvatars_Bottom.geometry} material={materials.UnionAvatars_Bottom} skeleton={nodes.UnionAvatars_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.UnionAvatars_Hair.geometry} material={materials['generated.png']} skeleton={nodes.UnionAvatars_Hair.skeleton} />
      <skinnedMesh geometry={nodes.UnionAvatars_Shoes.geometry} material={materials.UnionAvatars_Shoes} skeleton={nodes.UnionAvatars_Shoes.skeleton} />
      <skinnedMesh geometry={nodes.UnionAvatars_Top.geometry} material={materials.UnionAvatars_Top} skeleton={nodes.UnionAvatars_Top.skeleton} />
      <skinnedMesh geometry={nodes.Mesh.geometry} material={materials['model.jpg']} skeleton={nodes.Mesh.skeleton} />
      <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.UnionAvatars_Neck} skeleton={nodes.Mesh_1.skeleton} />
    </group>
  )
}

useGLTF.preload('/2b12NZh0CH30EQ5HjMDwTuDtuK2WIeonJSpJWc77wP1WrXJcX8RZOG.glb')
